// AUTO-GENERATED by AlmaIconsResolver
export const iconNames = [
  "back",
  "check",
  "cog",
  "cross",
  "down",
  "eyeDisabled",
  "eye",
  "login",
  "logout",
  "minus",
  "plus",
  "reload"
];
export const iconStyles = [
  "outline",
  "fill"
];
export const iconWeights = [
  "100",
  "200",
  "300",
  "400",
  "500",
  "600",
  "700"
];
